version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    command: mongod --auth
    restart: always
    build: ./
    ports:
      - "27017:27017"
    volumes:
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: project2
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig: